;====================================================================
; Main.asm file generated by New Project wizard
;
; Created:   Cum Mar 11 2016
; Processor: 8086
; Compiler:  MASM32
;
; Before starting simulation set Internal Memory Size 
; in the 8086 model properties to 0x10000
;====================================================================

;78H   01111000 cntr0
;7AH   01111010 cntr1
;7CH   01111100 cntr2
;7EH   01111110 control word register



STAK    SEGMENT PARA STACK 'STACK'
        DW 20 DUP(?)
STAK    ENDS


CODE    SEGMENT PARA 'CODE'
        ASSUME CS:CODE, SS:STAK
START:
 
     MOV AL,00110111B; 0 counter lsb msb mod3 bcd
     OUT 7EH,AL
     
     ; 2000000/4 = 500 000 = 1000 * 500
     MOV AX,1000H; 2m/1000 = 2000hz = saniyede 2000 dalga
     OUT 78H,AL
     MOV AL,AH
     OUT 78H,AL
     XOR AX,AX
     
     MOV AL,01110111B; 1 counter lsb msb mod3 bcd
     OUT 7EH,AL
     
     XOR AX, AX
     MOV AX,500H ;2000/500  = saniyede 4 dalga
     OUT 7AH,AL
     MOV AL,AH
     OUT 7AH,AL
     
 

ENDLESS:

 
 
        JMP ENDLESS
CODE    ENDS
        END START
