;====================================================================
; Main.asm file generated by New Project wizard
;
; Created:   Cum Mar 11 2016
; Processor: 8086
; Compiler:  MASM32
;
; Before starting simulation set Internal Memory Size 
; in the 8086 model properties to 0x10000
;====================================================================

;78H   01111000 cntr0
;7AH   01111010 cntr1
;7CH   01111100 cntr2
;7EH   01111110 control word register

;13.33k hz clock
;bizden istenen 1 pulse 
;13.33k  * 15 = 200k = 500 * 400
;lsb msb

;20H  00100000
;22H  00100010


STAK    SEGMENT PARA STACK 'STACK'
        DW 20 DUP(?)
STAK    ENDS

CODE    SEGMENT PARA 'CODE'
        ASSUME CS:CODE, SS:STAK

NEWINT PROC FAR
      PUSH BP
      MOV BP, SP
      INC AX
      POP BP
      IRET
NEWINT ENDP
      

START:


      MOV AL,00110101B;  0 counter -  lsb msb  - mod2  - bcd
      OUT 7EH,AL ; control word'e yükle

      MOV AX,500H
      OUT 78H,AL 
      MOV AL,AH
      OUT 78H,AL 
      
      
      MOV AL,01110101B; 1 counter -  lsb msb  - mod2  - bcd
      OUT 7EH,AL ; control word'e yükle

      MOV AX,400H
      OUT 7AH  ,AL 
      MOV AL,AH
      OUT 7AH ,AL
     
     ;ICW 
      
      XOR AX, AX ; ax'i sıfırla
      MOV ES, AX
      MOV AL, 40H ; 40h tipine karşılık hangi adresim var
      MOV AH, 4; 1 interrupts 4 byte yer kaplar 2 *segment + 2*offset
      MUL AH; adresi bul
      MOV BX, AX
      LEA AX, NEWINT ; fonksiyonun offset değerini vektör tablosunun hesapladığımız adresine at
      MOV WORD PTR ES:[BX], AX ; segment değerini doldur
      MOV AX ,CS; mevcut kod segmentimizi bunun iki ilerisine yaz (dönüş offseti)
      MOV WORD PTR ES:[BX+2], AX ; offset değerini doldur
 
      MOV AL, 13H; 00010011 - level trigger - single - IC4 needed
      OUT 20H, AL 

      MOV AL, 40H; 01000000 -  IR0'a kesme isteği gelir ve mikroişlemciye 01000000 aktarılır
      OUT 22H, AL

      MOV AL, 03H ; automatic end of interrupt 1 
      OUT 22H, AL

      STI ; set interrup flag 1
      XOR AX, AX
     
     
ENDLESS:


        JMP ENDLESS
CODE    ENDS
        END START
